# eval_config.yaml
path: C:\Users\Admin\PROJECT_LIPAD\Corrosion\LIPAD_YOLO_TRAINING\crack_detection\datasets\datasets
# Both train and val keys are strictly required by Ultralytics parser
train: images/train  # or 'train/images'
val: images/val      # or 'val/images'

names:
  0: crack